{
  gatedInfo: { contractAddress: '', eventLink: '', network: '', tokenId: '' },
  info: {
    socialTop: [
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object]
    ],
    videoUrl: [ [Object] ],
    socialLarge: [
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object]
    ],
    product: [ [Object], [Object] ],
    infoBar: [
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object]
    ],
    contact: [ [Object], [Object] ],
    ensDomain: [ [Object] ],
    blog: [ [Object] ],
    audio: [ [Object], [Object], [Object] ],
    video: [],
    redeemLink: [],
    referral: [ [Object], [Object] ]
  },
  _id: '65e58cb73b4e79ec49b722a8',
  parentId: '65e58cb43b4e79ec49b7227a',
  name: 'Raihan',
  bio: 'Business Analyst',
  brandImg: '',
  username: 'raihanmqru',
  profilePic: '30',
  backgroundImg: '7',
  profileUrl: 'https://swopme.app/sp/raihanmqru',
  pkPassUrl: 'https://res.cloudinary.com/bayshore/raw/upload/v1709640989/pass/vkjeahhkoqt49qu8gib5.pkpass',
  direct: null,
  totalTap: 195,
  gatedAccess: false,
  theme: true,
  ens: 'raihan.swop.id'
}